stages:
  preprocess_7k:
    cmd: python utils/preprocess_data.py --input data/telco_7k.csv --output data/telco_cleaned_7k.csv
    deps:
    - data/telco_7k.csv
    - utils/preprocess_data.py
    outs:
    - data/telco_cleaned_7k.csv
  simulate_1M:
    cmd: python utils/simulate_large_dataset.py --input data/telco_cleaned_7k.csv
      --output data/telco_cleaned_1M.csv --multiplier 150
    deps:
    - data/telco_cleaned_7k.csv
    - utils/simulate_large_dataset.py
    outs:
    - data/telco_cleaned_1M.csv
  train_model_7k:
    cmd: python utils/train_model.py --input data/telco_cleaned_7k.csv --model_output
      models/telco_churn_model_7k.pkl --metrics_output metrics/telco_metrics_7k.json
    deps:
    - data/telco_cleaned_7k.csv
    - utils/train_model.py
    - params.yaml
    outs:
    - metrics/telco_metrics_7k.json
    - models/telco_churn_model_7k.pkl
